### ISSUE TITLE
Failure with dev version of httr

### ISSUE THREAD

**Issue by hadley** [kalimu/genderizeR#2]
```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  6: condition(object)
  7: evaluate_promise(expr, print = TRUE)
  8: with_sink(temp, withCallingHandlers(withVisible(code), warning = wHandler, message = mHandler))
  9: withCallingHandlers(withVisible(code), warning = wHandler, message = mHandler)
  10: withVisible(code)
  11: genderizeAPI("Kamil", apikey = "test")
  12: httr::GET("https://api.genderize.io", query = query, httr::config(ssl.verifypeer = ssl.verifypeer))
  13: request_perform(req, hu$handle$handle) at /Users/hadley/Documents/web/httr/R/http-get.r:67
  14: curl::handle_setopt(handle, .list = req$options) at /Users/hadley/Documents/web/httr/R/request.R:119
  15: stop("Unknown options.") at /private/tmp/RtmpRrn4aZ/devtoolse6b2242dabf0/jeroenooms-curl-0911193/R/handle.R:49

  Error: Test failures
  Execution halted
```

Maybe because `ssl.verifypeer` is now `ssl_verifypeer`? But you really shouldn't be setting this anyway

**Comment by kalimu** [comment]
Thanks! You are right with ssl.verifypeer option - it should be gone in the next version. Although I have problem with testing it with dev version of  httr: when I try install it from github I get 
*\* testing if installed package can be loaded
**\* arch - i386
Error : package 'httr' is not installed for 'arch = i386'
Error: loading failed
Execution halted
**\* arch - x64
ERROR: loading failed for 'i386'
- removing 'C:/Program Files/R/R-3.2.0/library/httr'
- restoring previous 'C:/Program Files/R/R-3.2.0/library/httr'
  Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Program Files\R\R-3.2.0\library\00LOCK-hadley-httr-d6f24d8\httr\libs\x64\httr.dll to C:\Program Files\R\R-3.2.0\library\httr\libs\x64\httr.dll: Permission denied
  Error: Command failed (1)
  (I have Win7 64, R 3.2.0 and last version of RTools and curl installed)

**Comment by hadley** [comment]
Oh hmmmm - I think the problem might that you're installing it with devtools, and httr is one of the dependencies of devtools, and on windows you can't install over an existing package (if it contains C code). 

I think you'll have to manually clone the repo, build it, then restart R without loading devtools and `install.packages()`

**Comment by AugustT** [comment]
Probably not the best place for this comment but this was a high hit on Google for this error.

I get this same error when trying trying devtools::install_github("hadley/httr")

```
Error : package 'httr' is not installed for 'arch = i386'
```

I followed @hadley 's suggestion and this fixed the issue, allowing me to test my package functionality with the development version of httr.

**Comment by kalimu** [comment]
I finally spend some time on this fix and managed to install development version of httr (it was indeed possible with the suggestions from Hadley). Although, I still need to wait as Casper fix the issue with API sever overload to test fixes for genderizeR package. Hopefully it will be as soon as possible
. Thank you Hadley and August for your help!

**Comment by kalimu** [comment]
This issue was fixed in the recent version of the package. Already on CRAN.
