### ISSUE TITLE
country_id ? 

### ISSUE THREAD

**Issue by jmueller17** [kalimu/genderizeR#5]
The genderize.io allows for a country_id string to be passed along in the query. It looks like this is not working for this package, although crucial? Example "Andrea" in German is female, and in Italian male. Do you plan to add this or did I miss something?

**Comment by kalimu** [comment]
Hi, I am going to spend some time in the coming weeks on the next update of the package and I will surely consider implementation of this functionality. Thanks

**Comment by jmueller17** [comment]
Yes, that would be nice. Also: how about making available other gender APIs as well? There are at least two other good ones: https://gender-api.com/en/ and http://api.namsor.com/

**Comment by henlueth** [comment]
Any news on this? Thanks!

**Comment by tklebel** [comment]
If you still need the feature, @jmueller17 and @henlueth, you could try out the pull request via `devtools::install_github("tklebel/genderizeR")`.

**Comment by kalimu** [comment]
Hi All! The Thomas's code is merged now and will be available in the next CRAN release soon.
As for the other APIs, implementing them is not in my plan, but fill free to implement them an make your own pull request.
