### ISSUE TITLE
Failing to connect to Genderize.io on a free plan.

### ISSUE THREAD

**Issue by ghost** [kalimu/genderizeR#7]
Dear Kamil, 

first of all, genderizeR looks really promising. Thanks for the great work. However, I tried to make it work over the last couple of weeks without succeeding: Although just working with test data sets of a couple of names only, Genderize.io keeps telling me that I have reached the end of my rate plan. 

However, since my test data set contains only six names, this cannot be true. (Still given the premise of having 1000 free names per day). Did Genderize.io make any recent changes to their free plan? Can you spot any flaw in my attempts? 

Any hints are appreciated. Many thanks for your time. 

**Here's my code:** 

```
library("genderizeR")
x <- c("Maria", "Tom", "Michael", "Louisa", "Kristin", "Marvin")
forenameTest <- findGivenNames(x, textPrepare = TRUE, apikey = NULL, queryLength = 10,
               progress = TRUE, ssl.verifypeer = TRUE)

```
**Error message:**

>   |                                                  |   0%
 Client error: (429) Too Many Requests (RFC 6585)
 Request limit reached

The API queries stopped at 1 term. 
If you have reached the end of your API limit, you can start the function again from that term and continue finding given names next time with efficient use of the API.
 Remember to add the results to already found names and not to overwrite them. 

Warning messages:
1: In genderizeAPI(termsQuery, apikey = apikey, ssl.verifypeer = ssl.verifypeer) :
  You have used all available requests in this subscription plan.
2: In findGivenNames(x, textPrepare = FALSE, apikey = NULL, queryLength = 10,  :
  The API queries stopped. 

**And session info:**

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.6 (Sierra)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] genderizeR_2.0.0 rlist_0.4.6.1    gdata_2.17.0     plyr_1.8.4       Rfacebook_0.6.11 httpuv_1.3.3     rjson_0.2.15     httr_1.2.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8       gtools_3.5.0      slam_0.1-40       R6_2.2.0          jsonlite_1.4      magrittr_1.5      stringi_1.1.2    
 [8] curl_2.3          data.table_1.10.0 NLP_0.1-11        tools_3.3.1       stringr_1.1.0     parallel_3.3.1    tm_0.7-1         
> 

Many thanks

Marvin.

**Comment by kalimu** [comment]
Hi Marvin,
there is a problem with API itself. As far I know they are currently
working on resolving the issue in free plan. We should just wait a bit
longer. Paid plans should already work fine.

Best,
Kamil

**Comment by ghost** [comment]
Thanks so much for your swift reply, Kamil.

**Comment by ghost** [comment]
Hi Kamil, it works again. You can close this report now. Thanks again.

**Comment by pooja278786** [comment]
hi
i am getting this warning message:
Warning messages:
1: In genderizeAPI(termsQuery, apikey = apikey, ssl.verifypeer = ssl.verifypeer) :
  You have used all available requests in this subscription plan.
2: In findGivenNames(n1, textPrepare = TRUE, apikey = NULL, queryLength = 10,  :
  The API queries stopped. 
please help me how to tackle it.

**Comment by ghost** [comment]
Hi Pooja, 

seems like your requests were rate limited. Depending on your plan, you can only make a certain amount of requests.

Marvin
